---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lowesbui/public_html
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp styles.css $DEPLOYPATH/
    - /bin/cp app.js $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp -R assets/ $DEPLOYPATH/
